-- PROJETO BI SLOWLY CHANGE --
-- Author: JOAO PAULO VIEIRA RAMOS

-- Create table DIM_CLIENTE
CREATE TABLE public.DIM_CLIENTE
(
    SK_CLIENTE SERIAL NOT NULL,
    NK_CLIENTE INTEGER NOT NULL,
    NM_CLIENTE VARCHAR(255) NOT NULL,
    EMAIL_CLIENTE VARCHAR(120) NOT NULL,
    NM_CIDADE VARCHAR(60) NOT NULL, 
    DATA_INICIO TIMESTAMP NOT NULL,
    DATA_FIM TIMESTAMP, 
    FLAG_ATIVO CHAR(1) NOT NULL,
    CONSTRAINT PK_DIM_CLIENTE PRIMARY KEY("SK_CLIENTE")
)

-- CREATE TABLE DIM_PRODUTO 
CREATE TABLE public.DIM_PRODUTO
(
    SK_PRODUTO SERIAL NOT NULL,
    CD_CATEGORIA INTEGER NOT NULL,
    NM_CATEGORIA VARCHAR(60) NOT NULL,
    CD_SUB_CATEGORIA INTEGER NOT NULL,
    NM_SUB_CATEGORIA VARCHAR(60) NOT NULL,
    CD_PRODUTO VARCHAR(120) NOT NULL,
    NM_PRODUTO VARCHAR(60) NOT NULL,
    MARCA_PRODUTO VARCHAR(60) NOT NULL,
    PRECO_UNITARIO NUMERIC(12, 4) NOT NULL,
    DT_CARGA TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_PRODUTO PRIMARY KEY ("SK_PRODUTO")
)

-- CREATE TABLE DIM_TEMPO
CREATE TABLE public.DIM_TEMPO
(
    SK_DATA SERIAL NOT NULL,
    DATA DATE NOT NULL,
    DESC_DATA_COMPLETA VARCHAR(60) NOT NULL,
    NR_ANO INTEGER NOT NULL,
    NM_TRIMESTRE VARCHAR(20) NOT NULL, 
    NR_ANO_TRIMESTRE VARCHAR(20) NOT NULL,
    NM_MES VARCHAR(40) NOT NULL,
    NR_MES INTEGER NOT NULL,
    ANO_MES VARCHAR(20) NOT NULL,
    NR_SEMANA INTEGER NOT NULL,
    ANO_SEMANA VARCHAR(20) NOT NULL,
    NR_DIA INTEGER NOT NULL,
    NR_DIA_ANO INTEGER NOT NULL,
    NM_DIA_SEMANA VARCHAR(20) NOT NULL,
    FLAG_FINAL_SEMANA VARCHAR(3) NOT NULL,
    NM_FERIADO VARCHAR(60) NOT NULL,
    DT_CARGA TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_TEMPO PRIMARY KEY("SK_DATA")
)

-- CREATW TABLE DIM_GEOGRAFIA
CREATE TABLE DIM_GEOGRAFIA 
(
    SK_GEOGRAFIA SERIAL NOT NULL,
    NK_GEOGRAFIA VARCHAR(60) NOT NULL,
    NM_CIDADE VARCHAR(60) NOT NULL,
    NM_UF CHAR(2) NOT NULL,
    DT_CARGA TIMESTAMP NOT NULL,
    CONSTRAINT PK_DIM_GEOGRAFIA PRIMARY KEY("SK_GEOGRAFIA")

)


-- CREATE TABLE FATO_VENDA_DIARIO
CREATE TABLE FATO_VENDA_DIARIO
(
    SK_DATA INTEGER NOT NULL REFERENCES DIM_TEMPO("SK_DATA"),
    SK_PRODUTO INTEGER NOT NULL REFERENCES DIM_PRODUTO("SK_PRODUTO"),
    SK_CLIENTE INTEGER NOT NULL REFERENCES DIM_CLIENTE("SK_CLIENTE"),
    SK_GEOGRAFIA INTEGER NOT NULL REFERENCES DIM_GEOGRAFIA("SK_GEOGRAFIA"),
    DD_TRANSACAO VARCHAR(155) NOT NULL, 
    QTD_VENDA INTEGER NOT NULL,
    VL_DESCONTO NUMERIC(12,2) NOT NULL,
    VL_VENDA_COM_DESCONTO NUMERIC(12, 4) NOT NULL, 
    VL_VENDA_SEM_DESCONTO NUMERIC(12,4) NOT NULL, 
    DT_CARGA TIMESTAMP NOT NULL

)